### ISSUE TITLE
Clarification on LZSS's `elements_in_array` function

### ISSUE THREAD

**Issue by taufiq** [go-compression/go-compression.github.io#4]
Hey just read up on the LZSS implementation and I wanted to clarify the logic in the `elements_in_array` function.
[Link to page](https://go-compression.github.io/algorithms/lzss/#checking-the-search-buffer-for-more-characters)

This is the function:
```python
def elements_in_array(check_elements, elements):
    i = 0
    offset = 0
    for element in elements:
        if len(check_elements) <= offset:
            # All of the elements in check_elements are in elements
            return i - len(check_elements)

        if check_elements[offset] == element:
            offset += 1
        else:
            offset = 0

        i += 1
    return -1
```

I was wondering why the `<=` operator was used for `if len(check_elements) <= offset`. If you wanted to check if all the elements in `check_elements` are in `elements`, wouldn't the `==` operator suffice?

**Comment by phillipcutter** [comment]
Hey taufiq,

You're absolutely right, to check if all elements in `check_elements` are in `elements`, the `==` operator works instead of the `<=` operator. I think I wrote it that way because I learned that you should always write `while i > 10` not `while i != 10` in the impossible case that `i` is incremented twice and since then I try to change `==` operations on integers to include corner cases with less than or greater than signs.

**Comment by taufiq** [comment]
ahhh alright i see
